# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'UdacityMap' do
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  
end
